version: '2'
services:
    app1-app:
        image: app1
        external_links:
            - app1-mysql:mysql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
            - SPRING_CLOUD_CONFIG_URI=http://registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/app1?useUnicode=true&characterEncoding=utf8&useSSL=false
    app1-mysql:
        extends:
            file: mysql.yml
            service: app1-mysql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
